variable "region" {}
variable "project_name" {}
variable "vpc_cidr_block" {}
variable "subnet1_cidr_block" {}
variable "subnet2_cidr_block" {}
variable "rt_cidr_block" {}
variable "private_app_subnet1_cidr_block" {}
variable "private_app_subnet2_cidr_block" {}
variable "private_data_subnet1_cidr_block" {}
variable "private_data_subnet2_cidr_block" {}